### ISSUE TITLE
Permissions would be super cool here

### ISSUE THREAD

**Issue by ShareBtech** [FriendlyDotCH/mautic-multi-domain#11]
It would be great if the plugin added permissions so that this can be set for specific roles.

I found this good reference: https://github.com/mautic/developer-documentation/blob/main/source/includes/_plugin_permissions.md

**Comment by jos0405** [comment]
Hi, thank you for your feature request. I'll add it to the todo list.

**Comment by jos0405** [comment]
Hello,
I saw your additions regarding the permissions.
Thank you so much for contributing!
Let me know when I can test it and will merge it immediately.
Joey
