### ISSUE TITLE
how to uninstall this plugin?

### ISSUE THREAD

**Issue by zchli** [FriendlyDotCH/mautic-multi-domain#16]
Hi, I installed and used this plugin and it worked fine.

It’s just that all the links in my email have been modified to the new domain name, so I deleted the configuration of this plugin, but the links in the email did not restore to the system domain name I configured; then I deleted the plugin and cleared the cache directory. But the link in the email still hasn’t returned to the system domain name I configured.

I would like to ask how can I completely restore the domain name configured in my system.
or how to uninstall this plugin, is there steps could be added to README file.

many thanks!

**Comment by jos0405** [comment]
Remove the plugin and clear cache.
