### ISSUE TITLE
Forms  with mf-id return errors

### ISSUE THREAD

**Issue by kuzmany** [FriendlyDotCH/mautic-multi-domain#19]
These lines:

https://github.com/FriendlyDotCH/mautic-multi-domain/blob/main/EventListener/MultidomianSubscriber.php#LL124C15-L124C117

` $multidomainGenerateUrl = $this->router->generate('mautic_multidomain_action', ['id' => $mfId]);`

return  error 

> 500 Internal Server Error - Some mandatory parameters are missing ("objectAction") to generate a URL for route "mautic_multidomain_action". 

Do you have an update on it? It's just a concept?

**Comment by jos0405** [comment]
I'm not sure what this is. I think it's just a concept.

**Comment by kevin25** [comment]
I got 500 error
