### ISSUE TITLE
Problem installing on Mautic 4

### ISSUE THREAD

**Issue by AndiZu99** [FriendlyDotCH/mautic-multi-domain#2]
Hi I have tried to install this using the instructions provided in the MD file but have had no joy! When refreshing the plugins directory nothing changes and the msg says that there is 0 plugins to install & 0 Plugins to update! 

Please advise?

Regards 
AndiZu

**Comment by ilsebrase** [comment]
I initially had the same issue with version 3.3.4. but, i realised that i had to move the MauticMultiDomainBundle to the plugins level as it was a level too deep. this resolved it. i also had to login to mautic, refresh my plugins for the views on the multi domain navigation to work.  alll fine now.

**Comment by jos0405** [comment]
Thx for the feedback, glad it worked.
