### ISSUE TITLE
Not all links are changed 

### ISSUE THREAD

**Issue by peweb** [FriendlyDotCH/mautic-multi-domain#20]
I have just installed and tested this multidomain plugin and found some issues:

1. Message-ID: in the header uses the main domain instead of sending domain / aka masked domain.
Message-ID: <0a66434c84df7....16a3...f9b25@maindomain.com>

2. List-Unsubscribe: in the header uses the main domain
 <https://maindomain.com/email/unsubscribe/645bdc753.....97295726>

3. email/view URL points to the main domain
https://maindomain.com/email/view/645bdc7....97295726

4. Pixel uses the main domain
<img height="1" width="1" src="https://maindomain.com/email/645bdc7539....7295726.gif" alt="" />

There might be more issues.

Unsubscribe link works fine.

**Comment by jos0405** [comment]
Hi, which Mautic version are you using?

**Comment by peweb** [comment]
> 

448

**Comment by jos0405** [comment]
Thank you for the comment. I'll look into it. It has something to do with priorities.

**Comment by jos0405** [comment]
The tracking should be fixed now.
