### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by pavanobbeli** [FriendlyDotCH/mautic-multi-domain#25]
Team, I have manually installed this plugin https://github.com/FriendlyDotCH/mautic-multi-domain?tab=readme-ov-file and I am receiving an error when attempting to access Mautic. Could someone help me to resolve this issue?

<img width="859" alt="Repo_Issue" src="https://github.com/FriendlyDotCH/mautic-multi-domain/assets/32192097/445c88e2-1205-4736-b698-7f85cf160f9f">

**Comment by jos0405** [comment]
Are you working with Mautic 4 or 5? This is not M5 compatible yet
